### ISSUE TITLE
Markdown link broken

### ISSUE THREAD

**Issue by notes2c** [MicrosoftDocs/Contribute.da-DK#1]
Under section https://docs.microsoft.com/da-dk/contribute/dotnet-style-guide#basic-markdown-gfm-and-special-characters
The link to markdown (https://docs.microsoft.com/da-dk/contribute/how-to-write-use-markdown.md) is broken

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: 00bf1b48-5ec1-2623-e17e-73060ba79b78
* Version Independent ID: 27582428-2540-e724-96dd-e5990ef136dc
* Content: [Skabelon og notesark til .NET-artikler - Contributor Guide](https://docs.microsoft.com/da-dk/contribute/dotnet-style-guide#feedback)
* Content Source: [Contribute/dotnet-style-guide.md](https://github.com/MicrosoftDocs/Contribute.da-dk/blob/live/Contribute/dotnet-style-guide.md)
* Product: **non-product-specific**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @notes2c
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Thank you for your feedback. 

Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/da-dk/contribute/dotnet-style-guide#feedback.  

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards, 
Microsoft DOCS International Team
